version: '3.9'

services:

  postgres:

    image: postgres:16

    container_name: postgres-db

    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:

    build: .

    container_name: spring-backend

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devopsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:

    build: ./frontend

    container_name: react-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend